View-Products (back end) | Timothy Lee
timothywlee/off-white-shoes-shop pull request #1
Opened 2020-01-13 20:16 UTC by timmmleee

![Screen Shot 2020-01-13 at 12 12 24 PM](https://user-images.githubusercontent.com/55766322/72288732-8ce4ed80-35fe-11ea-914f-ccb1e6217eb0.png)

2020-01-13 20:55 UTC, thebearingedge requested changes
Please include your database export too.

2020-01-14 01:21 UTC, timmmleee commented
![Screen Shot 2020-01-13 at 5 21 20 PM](https://user-images.githubusercontent.com/55766322/72305604-2a551700-3629-11ea-8488-bdeb5abce0b9.png)

2020-01-14 01:24 UTC, timmmleee commented
<img width="640" alt="Screen Shot 2020-01-13 at 5 23 54 PM" src="https://user-images.githubusercontent.com/55766322/72305731-87e96380-3629-11ea-8f67-5aeda045360e.png">

2020-01-14 01:34 UTC, thebearingedge approved these changes

2020-01-14 01:36 UTC, merged